# Node Build and Validate and deploy on master push
name: Push Master CI

on:
  push:
    branches: 
      - master
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@master
      with:
        node-version: 10.x
    - name: npm ci, run validate
      run: |
        # TODO: set env for CI
        cp .env.sample .env
        npm ci
        npm run validate
    - name: Archive Build Artifact
      uses: actions/upload-artifact@master
      with:
        name: tc-api
        path: __build__


  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@master
        with:
          name: tc-api
      - name: Adjust files for FireBase
        run: |
          cd ./tc-api
          mkdir public
          mkdir -p functions/gateway
          mv graphql functions/gateway/graphql
          mv index.js functions/gateway/index.js
          mv package.json functions/package.json
          mv package-lock.json functions/package-lock.json
          mv .env functions/.env
      - name: Checks and verifications
        run: |
            echo $GITHUB_SHA
            echo $GITHUB_REF
            echo $PWD
            ls -lasiR
      - name: Use Node.js 10.x
        uses: actions/setup-node@master
        with:
          node-version: 10.x
      - name: Load node modules for Firebase
        run: |
          cd tc-api/functions
          pwd
          npm install
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting,functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          PROJECT_PATH: ./tc-api
